# Generated by Django 3.2.9 on 2023-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230728_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '实战课程'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
    ]
