# Generated by Django 3.2.9 on 2023-07-29 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20230729_1345'),
        ('users', '0003_auto_20230729_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_time',
            field=models.IntegerField(default=0, verbose_name='总学习时长'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/2021/avatar.jpg', null=True, upload_to='avatar/%Y/', verbose_name='个人头像'),
        ),
        migrations.AlterModelTable(
            name='credit',
            table='fg_credit',
        ),
        migrations.AlterModelTable(
            name='user',
            table='fg_users',
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称/标题')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('orders', models.IntegerField(default=0, verbose_name='序号')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_chapter', to='courses.coursechapter', verbose_name='章节信息')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_users', to='courses.course', verbose_name='课程名称')),
                ('lesson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_lesson', to='courses.courselesson', verbose_name='课时信息')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户课程购买记录',
                'verbose_name_plural': '用户课程购买记录',
                'db_table': 'ly_user_course',
            },
        ),
    ]
